"""Declarative transaction categorisation engine.

See docs/superpowers/specs/2026-07-09-categorisation-rules-engine-design.md
for the design this package implements. Two rule files share one schema:

- ``categorise/builtin_rules.yaml`` -- committed, structural, PII-free.
- ``category_rules.yaml`` (repo root) -- personal payee/merchant mappings,
  gitignored, generated by ``categorise/migrate_notebook_rules.py``.

Precedence: personal rules first, then builtin; within a file, first match
wins.
"""
